#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $LORASERVER_DB_USER PASSWORD '$LORASERVER_DB_PASSWORD';
    CREATE DATABASE $LORASERVER_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $LORASERVER_DB_NAME TO $LORASERVER_DB_USER;
EOSQL
