#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $LORAAPPSERVER_DB_USER PASSWORD '$LORAAPPSERVER_DB_PASSWORD';
    CREATE DATABASE $LORAAPPSERVER_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $LORAAPPSERVER_DB_NAME TO $LORAAPPSERVER_DB_USER;
EOSQL
